@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package info.loenwind.autosave.handlers.minecraft;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;