@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package info.loenwind.autosave.exceptions;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;