@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package info.loenwind.autosave.handlers;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;