@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package info.loenwind.autosave.handlers.internal;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;